### ISSUE TITLE
Token error :  it says token must be a string

### ISSUE THREAD

**Issue by ItsK4P** [IGRohan/IGBot#4]

**Comment by IGRohan** [comment]
token must be a string where? The discord bot token or.....?

**Comment by ItsK4P** [comment]
it says : SyntaxError: Invalid Token: Token must be a String

**Comment by IGRohan** [comment]
yea but where? there are a couple of places where it could ask for token. The error should include where the token is asked for.

**Comment by ItsK4P** [comment]
tell me where it ask for token cause it doesnt show the place

**Comment by IGRohan** [comment]
i think its on the joke and fml commands. You need an API key from [blague.xyz](https://www.blague.xyz).
Copy your api key and instead of placing in the .env file, directly place it in the jokes and fml command files. I'll fix the env file issue soon, till then use the API key directly.

In the joke.js file, you'll see this line ;--
```js
const joker = new Client(process.env.blagueApi, {
    defaultLang: "EN" //  The default language for jokes and fml  
});
```
change the `process.env.blagueApi` to `'YOUR_API_KEY'`
do the same for fml.js
